/*
 * Created: 07/02/2026
 * Last Edit: 07/02/026
 * Creator: Matthew Rivera
 * Description: Contains the array of data needed for a Pokémon
 *
 */

package Pokemon.Sub;

import Pokemon.Pokemon;
import Pokemon.Attack;

public class SubPokemon {
    public String[] names = {
            "Bulbasaur",
            "Ivysaur",
            "Venusaur",
            "Charmander",
            "Charmeleon",
            "Charizard",
            "Squirtle",
            "Wartortle",
            "Blastoise",
            "Caterpie",
            "Metapod",
            "Butterfree",
            "Weedle",
            "Kakuna",
            "Beedrill",
            "Pidgey",
            "Pidgeotto",
            "Pidgeot",
            "Rattata",
            "Raticate",
            "Spearow",
            "Fearow",
            "Ekans",
            "Arbok",
            "Pikachu",
            "Raichu",
            "Sandshrew",
            "Sandslash",
            "Nidoran♀",
            "Nidorina",
            "Nidoqueen",
            "Nidoran♂",
            "Nidorino",
            "Nidoking",
            "Clefairy",
            "Clefable",
            "Vulpix",
            "Ninetales",
            "Jigglypuff",
            "Wigglytuff",
            "Zubat",
            "Golbat",
            "Oddish",
            "Gloom",
            "Vileplume",
            "Paras",
            "Parasect",
            "Venonat",
            "Venomoth",
            "Diglett",
            "Dugtrio",
            "Meowth",
            "Persian",
            "Psyduck",
            "Golduck",
            "Mankey",
            "Primeape",
            "Growlithe",
            "Arcanine",
            "Poliwag",
            "Poliwhirl",
            "Poliwrath",
            "Abra",
            "Kadabra",
            "Alakazam",
            "Machop",
            "Machoke",
            "Machamp",
            "Bellsprout",
            "Weepinbell",
            "Victreebel",
            "Tentacool",
            "Tentacruel",
            "Geodude",
            "Graveler",
            "Golem",
            "Ponyta",
            "Rapidash",
            "Slowpoke",
            "Slowbro",
            "Magnemite",
            "Magneton",
            "Farfetch'd",
            "Doduo",
            "Dodrio",
            "Seel",
            "Dewgong",
            "Grimer",
            "Muk",
            "Shellder",
            "Cloyster",
            "Gastly",
            "Haunter",
            "Gengar",
            "Onix",
            "Drowzee",
            "Hypno",
            "Krabby",
            "Kingler",
            "Voltorb",
            "Electrode",
            "Exeggcute",
            "Exeggutor",
            "Cubone",
            "Marowak",
            "Hitmonlee",
            "Hitmonchan",
            "Lickitung",
            "Koffing",
            "Weezing",
            "Rhyhorn",
            "Rhydon",
            "Chansey",
            "Tangela",
            "Kangaskhan",
            "Horsea",
            "Seadra",
            "Goldeen",
            "Seaking",
            "Staryu",
            "Starmie",
            "Mr. Mime",
            "Scyther",
            "Jynx",
            "Electabuzz",
            "Magmar",
            "Pinsir",
            "Tauros",
            "Magikarp",
            "Gyarados",
            "Lapras",
            "Ditto",
            "Eevee",
            "Vaporeon",
            "Jolteon",
            "Flareon",
            "Porygon",
            "Omanyte",
            "Omastar",
            "Kabuto",
            "Kabutops",
            "Aerodactyl",
            "Snorlax",
            "Articuno",
            "Zapdos",
            "Moltres",
            "Dratini",
            "Dragonair",
            "Dragonite",
            "Mewtwo",
            "Mew",
    };

/*
    public Attack[][] attacks = {
            {Tackle, Growl, LeechSeed, VineWhip},
            {Tackle, Growl, LeechSeed, VineWhip},
            {VineWhip, PoisonPowder, RazorLeaf, Growth},
            {Scratch, Growl, Ember, Leer},
            {Ember, Leer, Rage, Slash},
            {Ember, Flamethrower, Slash, FireSpin},
            {Tackle, TailWhip, Bubble, WaterGun},
            {Bubble, WaterGun, Bite, Withdraw},
            {WaterGun, Bite, Withdraw, SkullBash},
            {Tackle, StringShot, Harden},
            {Harden},
            {Confusion, StunSpore, SleepPowder, Gust},
            {PoisonSting, StringShot, Harden},
            {Harden},
            {FuryAttack, Twineedle, Rage, PinMissile},
            {Gust, QuickAttack, Whirlwind, WingAttack},
            {Gust, QuickAttack, WingAttack, Whirlwind},
            {WingAttack, Agility, MirrorMove},
            {Tackle, TailWhip, QuickAttack, HyperFang},
            {QuickAttack, HyperFang, FocusEnergy, SuperFang},
            {Peck, Growl, Leer, FuryAttack},
            {Peck, DrillPeck, Leer, FuryAttack},
            {Wrap, Leer, PoisonSting, Bite},
            {PoisonSting, Bite, Glare, Acid},
            {ThunderShock, Growl, ThunderWave, QuickAttack},
            {ThunderShock, ThunderWave, Swift, Thunder},
            {Scratch, SandAttack, Slash, PoisonSting},
            {Slash, PoisonSting, FurySwipes},
            {Growl, Tackle, Scratch, PoisonSting},
            {Scratch, PoisonSting, TailWhip, DoubleKick},
            {Scratch, PoisonSting, TailWhip, DoubleKick},
            {HornAttack, PoisonSting, Thrash, FuryAttack},
            {Sing, DoubleSlap, Minimize, Metronome},
            {DoubleSlap, Minimize, Metronome, DefenseCurl},
            {Ember, TailWhip, QuickAttack, ConfuseRay},
            {Ember, QuickAttack, ConfuseRay, Flamethrower},
            {Sing, Pound, DefenseCurl, DoubleSlap},
            {Pound, DefenseCurl, DoubleSlap, BodySlam},
            {LeechLife, Supersonic, Bite, ConfuseRay},
            {LeechLife, Supersonic, Bite, ConfuseRay},
            {Absorb, PoisonPowder, StunSpore, SleepPowder},
            {Absorb, Acid, PoisonPowder, StunSpore},
            {Acid, PetalDance, StunSpore, SleepPowder},
            {Scratch, StunSpore, LeechLife, Slash},
            {LeechLife, StunSpore, Slash, Growth},
            {Tackle, Disable, Confusion, Supersonic},
            {Confusion, Disable, Supersonic, Psybeam},
            {Scratch, Growl, Dig, SandAttack},
            {Dig, SandAttack, Slash},
            {Scratch, Growl, Bite, PayDay},
            {Bite, PayDay, Screech, FurySwipes},
            {Scratch, TailWhip, Disable, Confusion},
            {Disable, Confusion, TailWhip, HydroPump},
            {Scratch, Leer, KarateChop, FurySwipes},
            {KarateChop, Leer, Rage, Submission},
            {Bite, Roar, Ember, Leer},
            {Ember, Leer, TakeDown, Flamethrower},
            {Bubble, Hypnosis, WaterGun, DoubleSlap},
            {Hypnosis, WaterGun, DoubleSlap, HydroPump},
            {Teleport, Confusion, Disable, Psybeam},
            {Confusion, Disable, Psybeam, Recover},
            {Confusion, Psybeam, Recover, Psychic},
            {KarateChop, LowKick, Leer, FocusEnergy},
            {LowKick, Leer, FocusEnergy, SeismicToss},
            {LowKick, Leer, FocusEnergy, Submission},
            {VineWhip, Growth, Wrap, Acid},
            {Wrap, Acid, RazorLeaf, SleepPowder},
            {Acid, RazorLeaf, SleepPowder, StunSpore},
            {Acid, Supersonic, Wrap, Barrier},
            {Acid, Wrap, Barrier, HydroPump},
            {Tackle, DefenseCurl, RockThrow, Selfdestruct},
            {DefenseCurl, RockThrow, Selfdestruct, Harden},
            {RockThrow, DefenseCurl, Selfdestruct, Earthquake},
            {Ember, TailWhip, Stomp, FireSpin},
            {Stomp, FireSpin, TailWhip, Growl},
            {Confusion, Disable, Headbutt, Growl},
            {Confusion, Disable, Headbutt, Withdraw},
            {Tackle, SonicBoom, ThunderShock, Supersonic},
            {SonicBoom, ThunderShock, Supersonic, Thunder},
            {Peck, FuryAttack, SwordsDance, Agility},
            {Peck, FuryAttack, Agility, TriAttack},
            {Growl, Headbutt, AuroraBeam, Rest},
            {Headbutt, AuroraBeam, Rest, IceBeam},
            {Pound, Disable, PoisonGas, Smog},
            {Disable, PoisonGas, Smog, Minimize},
            {Tackle, Withdraw, Supersonic, Clamp},
            {Withdraw, Supersonic, Clamp, IceBeam},
            {Lick, ConfuseRay, NightShade},
            {ConfuseRay, NightShade, Hypnosis, DreamEater},
            {NightShade, Hypnosis, DreamEater, ConfuseRay},
            {Tackle, Screech, Bind, RockThrow},
            {Hypnosis, Pound, Disable, Confusion},
            {Hypnosis, Disable, Confusion, Psychic},
            {Bubble, Leer, ViceGrip, Harden},
            {ViceGrip, Harden, Leer, Crabhammer},
            {Tackle, Screech, SonicBoom, Selfdestruct},
            {Screech, SonicBoom, Selfdestruct, Explosion},
            {Barrage, Hypnosis, Reflect, LeechSeed},
            {Hypnosis, Barrage, Stomp, SolarBeam},
            {BoneClub, Growl, FocusEnergy, Bonemerang},
            {BoneClub, FocusEnergy, Bonemerang, Rage},
            {DoubleKick, Meditate, RollingKick, JumpKick},
            {CometPunch, Agility, FirePunch, IcePunch},
            {Lick, Supersonic, Stomp, Disable},
            {PoisonGas, Tackle, Smog, Sludge},
            {Tackle, Smog, Sludge, Haze},
            {HornAttack, Stomp, TailWhip, FuryAttack},
            {Stomp, TailWhip, FuryAttack, HornDrill},
            {Pound, DoubleSlap, Minimize, Sing},
            {Constrict, Bind, Absorb, StunSpore},
            {CometPunch, Rage, Bite, TailWhip},
            {Bubble, Smokescreen, Leer, WaterGun},
            {Smokescreen, Leer, WaterGun, HydroPump},
            {Peck, TailWhip, HornAttack, FuryAttack},
            {HornAttack, FuryAttack, Agility},
            {Tackle, Harden, WaterGun, Recover},
            {Harden, WaterGun, Recover, HydroPump},
            {Barrier, Confusion, LightScreen, Reflect},
            {QuickAttack, Leer, FocusEnergy, Slash},
            {Pound, Lick, LovelyKiss, IcePunch},
            {QuickAttack, Leer, ThunderPunch, ThunderShock},
            {Ember, Leer, Smokescreen, FirePunch},
            {ViceGrip, SeismicToss, Harden, Bind},
            {Stomp, TailWhip, Leer, Rage},
            {Splash, Tackle},
            {Tackle, Bite, DragonRage, HydroPump},
            {WaterGun, Growl, Sing, IceBeam},
            {Transform},
            {Tackle, TailWhip, SandAttack, Growl},
            {WaterGun, QuickAttack, TailWhip, AuroraBeam},
            {ThunderShock, QuickAttack, TailWhip, ThunderWave},
            {Ember, QuickAttack, TailWhip, FireSpin},
            {Tackle, Sharpen, Conversion, TriAttack},
            {WaterGun, HornAttack, Leer, SpikeCannon},
            {HornAttack, Leer, SpikeCannon, HydroPump},
            {Scratch, Harden, Absorb, Slash},
            {Absorb, Slash, Harden, HydroPump},
            {WingAttack, Agility, Supersonic, HyperBeam},
            {Headbutt, Rest, BodySlam, HyperBeam},
            {Peck, IceBeam, Blizzard, Agility},
            {ThunderShock, Agility, ThunderWave, DrillPeck},
            {Ember, Leer, FireSpin, Agility},
            {Wrap, ThunderWave, Slam, DragonRage},
            {DragonRage, Slam, Agility, HyperBeam},
            {HyperBeam, Slam, Agility},
            {Confusion, Disable, Psychic, Recover},
            {Pound, Transform, MegaPunch, Psychic}

    };
*/
    public int[] type = {
            12,
            12,
            12,
            9,
            9,
            9,
            10,
            10,
            10,
            6,
            6,
            6,
            6,
            6,
            6,
            2,
            2,
            2,
            0,
            0,
            2,
            2,
            3,
            3,
            11,
            11,
            4,
            4,
            3,
            3,
            3,
            3,
            3,
            3,
            0,
            0,
            9,
            9,
            0,
            0,
            3,
            3,
            12,
            12,
            12,
            6,
            6,
            6,
            4,
            4,
            0,
            0,
            10,
            10,
            1,
            1,
            9,
            9,
            10,
            10,
            10,
            14,
            14,
            14,
            1,
            1,
            1,
            12,
            12,
            12,
            10,
            10,
            5,
            5,
            5,
            9,
            9,
            10,
            10,
            11,
            11,
            0,
            2,
            2,
            2,
            10,
            10,
            3,
            3,
            10,
            10,
            7,
            7,
            7,
            5,
            14,
            14,
            10,
            10,
            11,
            11,
            12,
            12,
            4,
            4,
            1,
            1,
            0,
            3,
            3,
            5,
            5,
            0,
            12,
            0,
            10,
            10,
            10,
            10,
            10,
            14,
            6,
            14,
            11,
            9,
            6,
            0,
            10,
            10,
            0,
            0,
            10,
            11,
            11,
            9,
            12,
            12,
            5,
            5,
            5,
            5,
            13,
            13,
            14,
            14,
            14,
            14,
            14,
    };
}
